In [5]:
import numpy as np

In [7]:
arry = np.array([1,2,3,4,5])
arry

array([1, 2, 3, 4, 5])

In [9]:
num = np.random.randn(3)
num

array([-0.77573542, -0.67808327, -1.55956398])

In [17]:
num1 = np.random.randint(20,50,10)
num1

array([31, 33, 36, 35, 22, 20, 39, 39, 40, 21])

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr. shape

(3, 3)

In [81]:
arr.size

1

In [104]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [106]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [107]:
arr.mean

<function ndarray.mean>

In [108]:
arr.mean()

np.float64(5.0)

In [109]:
arr.std()

np.float64(2.581988897471611)

In [110]:
arr.argmax()

np.int64(8)

In [111]:
arr.argmin()

np.int64(0)

In [112]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [113]:
arr = arr.reshape(6,5)

In [114]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [115]:
arr[0]

array([1, 2, 3, 4, 5])

In [116]:
arr[5]

array([26, 27, 28, 29, 30])

In [117]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [118]:
arr[0,0]

np.int64(1)

In [121]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [122]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [124]:
arr  = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [125]:
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [126]:
index_bool = arr % 2 == 0 

In [127]:
index_bool

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [128]:
arr = arr[index_bool]

In [134]:
arr

array([12, 14, 16, 18, 20])

In [149]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [150]:
slice = a[:5]

In [151]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [152]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [153]:
a
b = a.copy()

In [154]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [155]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [156]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [161]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [162]:
A

array([[1, 2],
       [3, 4]])

In [163]:
B

array([[5, 6],
       [7, 8]])

In [165]:
A.T

array([[1, 3],
       [2, 4]])

In [166]:
B.T


array([[5, 7],
       [6, 8]])

Advanced Array Manuplation


Stacking Array

In [167]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [168]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [169]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [170]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [173]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [174]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]